channels:
- conda-forge
- defaults
- soumith
dependencies:
- h5py
- flake8
- ipython
- jedi
- jupyter
- matplotlib
- numpy
- pandas
- pip
- pyflakes
- python=3.5
- scikit-learn
- scipy
- seaborn
- pyyaml
- mkl
- setuptools
- cmake
- gcc
- cffi
- tqdm
# - torchvision
# - magma-cuda80
- pillow
- pip:
  - autoflake
  - autopep8
  - elpy
  - importmagic
  - opencv-python
  - yapf
