name: kaggle-amazon-from-space
channels:
- conda-forge
- defaults
dependencies:
- h5py
- flake8
- ipython
- jedi
- jupyter
- matplotlib
- numpy
- pandas
- pip
- pyflakes
- python=3.5
- scikit-learn
- scipy
- seaborn
- pip:
  - autoflake
  - autopep8
  - elpy
  - importmagic
  - opencv-python
  - yapf
